# Generated by Django 3.2.6 on 2021-09-26 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user', verbose_name='user')),
                ('avatar_url', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
