# Generated by Django 3.2.6 on 2021-09-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verified_email',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
