# Generated by Django 3.2.6 on 2021-10-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211014_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
