# Generated by Django 3.2.6 on 2021-10-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211014_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
