# Generated by Django 3.2.6 on 2021-10-14 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.blog'),
        ),
    ]
